### ISSUE TITLE
Width and height are not set for large icons (addBadge)

### ISSUE THREAD

**Issue by Tersaramor** [jenkinsci/badge-plugin#148]
### Jenkins and plugins versions report

<details>
<summary>Jenkins: 2.440.3, Java 11.0.13, and plugins</summary>
<pre>
OS: Linux - 5.4.0-90-generic
Java: 11.0.13 - Ubuntu (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.2.0
allure-jenkins:3.29.0
allure-jenkins-plugin:2.31.1
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-1.0
asm-api:9.7-33.v4d23ef79fcc8
authentication-tokens:1.53.v1c90fd9191a_b_
badge:1.10
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1169.va_f810c56e895
build-name-setter:2.4.2
build-timeout:1.32
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.901.vb_4c7a_da_75da_3
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-109.vfe16c66636eb_
conditional-buildstep:1.4.3
config-file-provider:973.vb_a_80ecb_9a_4d0
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:677.vdc9d38cb_254d
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:439.va_3cb_0a_6a_fb_29
docker-compose-build-step:1.0
docker-java-api:3.3.4-86.v39b_a_5ede342c
docker-plugin:1.6.1
docker-workflow:572.v950f58993843
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
extended-read-permission:53.v6499940139e5
font-awesome-api:6.5.2-1
generic-webhook-trigger:2.2.1
git:5.2.2
git-client:4.7.0
git-server:117.veb_68868fa_027
google-oauth-plugin:1.330.vf5e86021cb_ec
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.10.1-15.v0d99f670e0a_7
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jersey2-api:2.42-147.va_28a_44603b_d5
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1265.v65b_14fa_f12f0
ldap:725.v3cb_b_711b_1a_ef
leastload:3.0.0
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.1-101.v85b_e08b_780dd
mina-sshd-api-core:2.12.1-101.v85b_e08b_780dd
oauth-credentials:0.646.v02b_66dc03d2e
pam-auth:1.10
parameterized-scheduler:262.v00f3d90585cc
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2198.v41dd8ef6dd56
pipeline-model-definition:2.2198.v41dd8ef6dd56
pipeline-model-extensions:2.2198.v41dd8ef6dd56
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2198.v41dd8ef6dd56
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:179.vc5cb_98f6db_38
plugin-usage-plugin:4.4
plugin-util-api:4.1.0
rebuild:332.va_1ee476d8f6d
resource-disposer:0.23
role-strategy:727.vd344b_eec783d
run-condition:1.7
scm-api:690.vfc8b_54395023
script-security:1336.vf33a_a_9863911
sidebar-link:2.4.1
simple-theme-plugin:176.v39740c03a_a_f5
slack:715.v1cfed1b_9c63c
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-agent:367.vf9076cd4ee21
ssh-credentials:337.v395d2403ccd4
ssh-slaves:2.948.vb_8050d697fec
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
theme-manager:215.vc1ff18d67920
throttle-concurrents:2.14
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3894.3896.vca_2c931e7935
workflow-durable-task-step:1336.v768003e07199
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:907.v6713a_ed8a_573
</rep>
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

1. addBadge with large icon `addBadge(icon: relativeIconPath, text: displayName, link: url)`

### Expected Results

Icon is 16x16
<img width="54" alt="image" src="https://github.com/jenkinsci/badge-plugin/assets/83928448/1b3084d3-fb25-4b56-8981-216f4a23bb1b">

### Actual Results

icon has actual size
<img width="304" alt="image" src="https://github.com/jenkinsci/badge-plugin/assets/83928448/475a3d73-72df-495c-9d5c-d024dc700e5d">

### Anything else?

Probably related to https://github.com/jenkinsci/badge-plugin/pull/130/files

<img width="1672" alt="image" src="https://github.com/jenkinsci/badge-plugin/assets/83928448/f1c22ad0-2c93-48b7-aae5-31ca3bc44cf7">

**Comment by MarkEWaite** [comment]
@Tersaramor I've attempted a fix for the bug.  Could you confirm that the [incremental build](https://ci.jenkins.io/job/Plugins/job/badge-plugin/job/PR-149/) works well in your environment?  The incremental build should be ready in less than 30 minutes

**Comment by timonwalkley** [comment]
It looks like we're still experiencing this issue on v1.12.

The larger images are coming from /images/svg...

`addBadge(icon: "/images/svgs/logo.svg")`

![image](https://github.com/jenkinsci/badge-plugin/assets/34693931/da478b4e-361e-47df-95ba-07583200d91f)

**Comment by strangelookingnerd** [comment]
Hey @timonwalkley. Sorry you still need to deal with this issue. I can reproduce it, however I _think_ it has to do with the SVG itself as it does have some sort of sizing attached to it which I'm not sure we can actually override. I'll look a little deeper into it and come back to you as soon as possible.

**Comment by strangelookingnerd** [comment]
From what I can tell this happens for the "core" icons that can be referenced as either `addBadge(icon: "/images/svgs/logo.svg")` or `addBadge(icon: "icon-logo 16")` (the latter not being supported yet by this plugin).

It appears that in [icon.jelly](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/lib/layout/icon.jelly) it is determined _hey, this is a core icon_ using [Functions](https://github.com/jenkinsci/jenkins/blob/33b22bc7fa83f90e8412ad3efe87057d05c6b09b/core/src/main/java/hudson/Functions.java#L2391) and [IconSet](https://github.com/jenkinsci/jenkins/blob/33b22bc7fa83f90e8412ad3efe87057d05c6b09b/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L131). There it is decided _hey, since this is a core icon it has this size_ which it then used for the style.

This functionallity is rather complex and can likely not be adapted even though one could argue that overridding the actual given css class could be considered a bug.

Maybe someone from @jenkinsci/sig-ux could share some insights here or confirm my observations.

As of now it seems the only remedy is to hard-code the icon `style="width: 16px; height: 16px;"` in the plugin.

**Comment by timja** [comment]
can't you add something like the class `icon-sm` ?

**Comment by strangelookingnerd** [comment]
We already do that, but it does not seem to work for these icons - or at least not always.
On my refactoring branch (#151) I can see that:

```
<span class="${it.cssClass}" style="${it.style}">
    <l:icon class="icon-sm" src="${it.icon}" alt="${it.text}" htmlTooltip="${it.text}"/>
</span>
```

does produce icons with width and height set to 48px when used with `addBadge(icon: "/images/svgs/logo.svg")` whereas:

```
<span class="${it.cssClass}" style="${it.style}">
    <l:icon class="icon-sm" style="width: 16px; height: 16px;" src="${it.icon}" alt="${it.text}" htmlTooltip="${it.text}"/>
</span>
```

works perfectly fine. Right now I fail to reproduce it on master (but I'm certain I did just an hour ago)

**Comment by timja** [comment]
I would be wary of defaulting to html for tooltips but that code looks fine

**Comment by strangelookingnerd** [comment]
Ok, now I get it - there is something fishy with how the path to the icon is determined in my local environment. Anyways:

```
<l:icon src="/images/svgs/logo.svg" class="icon-sm" />
```
results in the icon

![grafik](https://github.com/jenkinsci/badge-plugin/assets/49242855/53e2977c-0718-4206-bb14-bd0d054855dd)
![grafik](https://github.com/jenkinsci/badge-plugin/assets/49242855/e7e7f2c4-ee0f-485d-8162-6da8027b6442)


However 

```
<l:icon src="/jenkins/static/40c46706/images/svgs/logo.svg" class="icon-sm" />
```

results in 

![grafik](https://github.com/jenkinsci/badge-plugin/assets/49242855/27196922-5de9-403f-a070-43f7ec4c7baa)
![grafik](https://github.com/jenkinsci/badge-plugin/assets/49242855/ba16b083-d541-4e4a-b44d-4d9afd013046)

**Comment by strangelookingnerd** [comment]
I tried to dig a little deeper into it and found that in https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L492-L497 all "core" svg are being added as icons for all the existing sizes. However in https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/org/jenkins/ui/icon/IconSet.java#L87-L89 they are added to the `iconsByUrl` map with their URL as key which is the same, no matter the size. Therefor the map contains those core icons only with the 48x48 / icon-xlg size. This map is used by [`icon.jelly`](https://github.com/jenkinsci/jenkins/blob/33b22bc7fa83f90e8412ad3efe87057d05c6b09b/core/src/main/resources/lib/layout/icon.jelly#L62) via https://github.com/jenkinsci/jenkins/blob/33b22bc7fa83f90e8412ad3efe87057d05c6b09b/core/src/main/java/hudson/Functions.java#L2413

This means if i build an icon using `/images/svgs/logo.svg` I will always end up with the 48x48 variant. If i however use `/jenkins/static/40c46706/images/svgs/logo.svg` there is no entry for it in the map and I will therefor not use the icons style https://github.com/jenkinsci/jenkins/blob/33b22bc7fa83f90e8412ad3efe87057d05c6b09b/core/src/main/resources/lib/layout/icon.jelly#L66

**Comment by timja** [comment]
nice analysis. I'm sure it could be cleaned up, but would require some testing and analysis...

**Comment by jonsgity** [comment]
We are on Badge 1.12 and getting this sometimes when jobs are added to the queue:
![image](https://github.com/jenkinsci/badge-plugin/assets/6684576/4b7453ef-e2e4-4dec-8391-abb99dd9f70d)

Is this the same issue?
It goes away after several seconds and after refreshing the page.  After that, the job appear in the queue as usual.

**Comment by MarkEWaite** [comment]
@jonsgity that does not seem like it is related to the badge plugin or at least it is a very different behavior than any other report.  Please open a new issue and include the stack trace that has likely been written to the Jenkins log file when that message appears.

You can also test the build of this pull request in your environment to confirm that it does not resolve the issue.  The "Checks" tab includes a section called "Incrementals".  The page in that section provides a URL where you can download the build of this pull request.
