### ISSUE TITLE
link on addErrorBadge not working

### ISSUE THREAD

**Issue by quasarea** [jenkinsci/badge-plugin#17]
Using: 

        addErrorBadge (
            text: "Unit tests failed for ${project.Name}", 
            link: "${env.BUILD_URL}testReport"
        )

will not produce clickable badge, 

Using workaround

        addBadge(
            icon: "error.gif",
             text: "Unit tests failed for ${project.Name}", 
            link: "${env.BUILD_URL}testReport"
        )

**Comment by bakito** [comment]
Hi 

I could extend the behavior of the status icons. They support now links as well.

**Comment by quasarea** [comment]
Thanks

**Comment by bakito** [comment]
Released wit version 1.7
