### ISSUE TITLE
Creating simple badge with rounded borders

### ISSUE THREAD

**Issue by thweiss** [jenkinsci/badge-plugin#177]
### Describe your use-case which is not covered by existing documentation.

The documentation shows a simple badge with rounded corners and lightgrey background for build 8 with text "1.0.0" and a tooltip:
![badge](https://github.com/user-attachments/assets/f002fc53-76e6-4a95-b5f7-e030a00e3505)

Assuming it was generated with `addShortText(text: <text>)`, I have not been able to create a similar looking badge.
The closest I could get with `addShortText` is rather ugly:
![badge_addShortText](https://github.com/user-attachments/assets/7d7d1227-840c-4356-80f5-1eef6e319ae6)

Please describe how to create a badge with the same styling as first one on your screenshot (ideally without custom CSS).

I'm using Jenkins v2.452.1 with Badge v1.13.

**Comment by strangelookingnerd** [comment]
By using `addShortText(text: "1.0.0", border: "0", background: "lightgrey; border-radius: 5px")` I got this result

![grafik](https://github.com/user-attachments/assets/a7043e07-a2b9-4e37-8122-c99391bbbed2)

By using `addShortText(text: "1.0.0", border: "1", borderColor: "lightgrey", background: "lightgrey; border-radius: 5px")` I got this result

![grafik](https://github.com/user-attachments/assets/18b05a28-e915-481b-99d7-4ff8b4eb461d)


There may be other ways to achieve this result I guess.

**Comment by thweiss** [comment]
Thanks, applying `padding: 2px` with `border: "0"` I could also achieve similar results.
However, I noticed the build history for that particular job will occupy a lot of space because the badge(s) will be put above the timestamp even though they could well fit right next to it. Also, any additional info badges will not end next to short text badges but below them (see screenshot).

![Screenshot 2024-08-09 194910](https://github.com/user-attachments/assets/c24b2ec0-c058-4349-8d17-3614ae3d12fa)

Is there anything I can do about those spacing issues?

**Comment by strangelookingnerd** [comment]
> Is there anything I can do about those spacing issues?

The overall layout is handled outside of the plugin so there is not too much I could think of. However the [redesign](https://github.com/jenkinsci/jenkins/pull/9148) of the enclosing build history widget was released recently and brings a lot of improvements that may fix this particular issue.

**Comment by thweiss** [comment]
Ah, good to know there will be some general improvements soon. Already expected it will involve altering the markup of the divs that are not under control of the plugin. 

I'll close this issue then as I received the information I wanted: the user needs to provide their own CSS to achieve results similar to the badge on the first screenshot of the documentation which was not immediately obvious.
