### ISSUE TITLE
version 2.0 is incompatible and breaks groovy-postbuild plugin

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/badge-plugin#189]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

doesn't matter

### Reproduction steps

https://github.com/jenkinsci/groovy-postbuild-plugin/blob/6eeecb7aeac5faa75313280ad67ad4c938e5bdc0/src/main/java/org/jvnet/hudson/plugins/groovypostbuild/GroovyPostbuildRecorder.java#L214 creates a new instance of BadgeSummaryAction
I don't know the exact conditions when the code is called but it results in this stacktrace
```
[2024-09-18T03:04:30.919Z] java.lang.NoSuchMethodError: 'void com.jenkinsci.plugins.badge.action.BadgeSummaryAction.<init>(java.lang.String)'
[2024-09-18T03:04:30.919Z] 	at PluginClassLoader for groovy-postbuild//org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder$BadgeManager.createSummary(GroovyPostbuildRecorder.java:214)
[2024-09-18T03:04:30.919Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-09-18T03:04:30.919Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
```

### Expected Results

badge is properly created

### Actual Results

build fails

**Comment by strangelookingnerd** [comment]
My suggestion is to upgrade the groovy-postbuild-plugin in order to be compatible (I had that on my bucket list anyway). WDYT?

**Comment by mawinter69** [comment]
definitely a solution

**Comment by mawinter69** [comment]
Once groovy-postbuild is adjusted I think the release notes should be updated to mention that groovy-postbuild must be updated as well

**Comment by MarkEWaite** [comment]
A pre-release of the groovy postbuild plugin is available for testing.  Use the ["Jenkins Incrementals Publisher" tab](https://github.com/jenkinsci/groovy-postbuild-plugin/pull/81/checks) to access the most recent build.

**Comment by knapsu** [comment]
Thanks @MarkEWaite. The most recent build fixes the issue.

**Comment by strangelookingnerd** [comment]
Fixed in release [264.vf6e02a_77d5b_c](https://github.com/jenkinsci/groovy-postbuild-plugin/releases/tag/264.vf6e02a_77d5b_c) of the groovy postbuild plugin.
