### ISSUE TITLE
BlueOcean render with message

### ISSUE THREAD

**Issue by quasarea** [jenkinsci/badge-plugin#19]
Would be great to be able to see message on the badge in blue ocean, now it looks like:
![image](https://user-images.githubusercontent.com/10334982/54602601-02f9e180-4a3a-11e9-93da-be7796d6810b.png)
Something like:
![image](https://user-images.githubusercontent.com/10334982/54602668-3177bc80-4a3a-11e9-8721-1b1ac4f5b64e.png)
would be great, or even:
![image](https://user-images.githubusercontent.com/10334982/54602734-5ff59780-4a3a-11e9-8e3b-97f1099150e7.png)
would do!

**Comment by quasarea** [comment]
oh, it looks like its already does it, just its blue inconsistency that sometimes shows it and sometimes it does not:
![image](https://user-images.githubusercontent.com/10334982/54603430-2de53500-4a3c-11e9-986a-fd0bbfc6e605.png)

**Comment by bakito** [comment]
I don't know how the output to blueocean is written.

Can you help me?

**Comment by quasarea** [comment]
I have no clue either, but it is surely blueocean issue not badges ;)
