### ISSUE TITLE
disableFormatHTML: false destroys JCaC yaml file

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/badge-plugin#194]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

We are using JCaC yaml file to allow HTML format in the badge plugin
``` yaml
badgePlugin:
    disableFormatHTML: false
```

Feadback from my coworker after update to 2.0 version

> Sooo there was a problem with the yaml configuration.
It says it cant read the property 
I removed it now from the yaml and it works again, but we did no change there and also no update, i don't know why this happened, but i need to leave now
 

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Official latest LTS docker image (Debian)
Agents: It does not matter in this case

### Reproduction steps

Try to import JCaC yaml file that contains

``` yaml
badgePlugin:
    disableFormatHTML: false
```

### Expected Results

Jenkins instance should starts, when the property is obsolote, it shall be a warning thrown, but in all cases Jenkins should start

### Actual Results

Jenkins instance will not start

**Comment by strangelookingnerd** [comment]
See https://github.com/jenkinsci/badge-plugin/releases/tag/badge-2.0

> 💥 HTML formatting delegated to global Jenkins MarkupFormatter
> Breaking: Remove Badge Plugin global configuration
> This will mostly affect usage in JCasC but also may impact some visualization, see next points

I will add another clarification for JCasC users.
