### ISSUE TITLE
Is it possible to add link in the addShortText dsl?

### ISSUE THREAD

**Issue by scheibinger** [jenkinsci/badge-plugin#2]
Is there a way to add the text link rather than icon link?

Any chance to get addShortText api enhanced in the following way?:

`addShortText(text, escapeHtml)`

**Comment by bakito** [comment]
I could add the link like
`addShortText(text, link)  `

What do you mean with 
`addShortText(text, escapeHtml)`
Would you want to provide some custom thml for the short text?

**Comment by scheibinger** [comment]
It would more flexible to just allow anyone to pass the snippet and turn off escaping using the escapeHtml flag.  Similar to createSummary function.

This way anyone could create a link or even customize its style. Or use this function for displaying any short html snippet.

**Comment by bakito** [comment]
I've added a new dsl function to add a html badge, which supports only html.
 @scheibinger Does this suite your needs?

**Comment by scheibinger** [comment]
Thanks so much @bakito This is exactly what I need.
