### ISSUE TITLE
support `.jenkins-table` css for `addSummary`

### ISSUE THREAD

**Issue by marslo** [jenkinsci/badge-plugin#220]
### What feature do you want to see added?

I'm trying to create a table with `.jenkins-table` css in build summary, by following [the example in design-library/Table](https://weekly.ci.jenkins.io/design-library/Table/).

Here is the sample Jenkinsfile:

```groovy
#!/usr/bin/env groovy

def table = addSummary icon: 'symbol-terminal',
                       text: '''
                               <h2>PIPELINE DETAILS</h2>
                                <table class="jenkins-table sortable jenkins-!-margin-bottom-0">
                                  <thead>
                                    <th>NAME</th>
                                    <th>STATUS</th>
                                    <th>REASON</th>
                                  </thead>
                                  <tbody>
                                  <tr>
                                    <td><a href="#" class="jenkins-table__link">Link 1</a></td>
                                    <td>Success <a href="#" class="jenkins-table__link jenkins-table__badge model-link inside">#7</a></td>
                                    <td>No Errors</td>
                                  </tr>
                                  <tr>
                                    <td><a href="#" class="jenkins-table__link">Link 2</a></td>
                                    <td>Failure</td>
                                    <td>Can't compile</td>
                                  </tr>
                                  <tr>
                                    <td><a href="#" class="jenkins-table__link">Link 3</a></td>
                                    <td>Unstable</td>
                                    <td>Test Failed</td>
                                  </tr>
                                  </tbody>
                                </table>
                             '''.stripIndent()

println table.getText()
```

However, seems the Jenkins trim the css from the HTML ( `text: <..html..>` ), and it looks as below:
<img width="753" alt="Image" src="https://github.com/user-attachments/assets/583b628f-9f99-4ead-ac90-12cdf74495f8" />

When I manually added the Jenkins official css in HTML, it works ( as below )
- dark theme
  ![Image](https://github.com/user-attachments/assets/41698d54-d807-4c6a-9036-3a623e8c4a66)

- light theme
  ![Image](https://github.com/user-attachments/assets/c075c2cc-250b-402c-b25e-bbddf6608ce0)

I'd like to know how to enable the official table css `class="jenkins-table sortable jenkins-!-margin-bottom-0"` for table content ?

---------

By the way, I've noticed that the `addSummary` will consider the `<table><thead>..</thead></table>` as a separated table, and the `<thead>..</thead>` will be re-format into `<tbody>..</tbody>` :

<table><thead>
  <tr>
    <th>ORIGINAL</th>
    <th>RESULT</th>
  </tr></thead>
<tbody>
  <tr>
      <td><pre>&lt;table&gt;<br>  &lt;thead&gt;<br>    &lt;th&gt;NAME&lt;/th&gt;<br>    &lt;th&gt;STATUS&lt;/th&gt;<br>    &lt;th&gt;REASON&lt;/th&gt;<br>  &lt;/thead&gt;<br>&lt;/table&gt;</pre></td>
      <td><pre>&lt;table&gt;<br>&nbsp;&nbsp;&lt;thead&gt;&lt;/thead&gt;<br>&lt;/table&gt;<br><br>&lt;table&gt;<br>  &lt;tbody&gt;<br>    &lt;tr&gt;<br>      &lt;th&gt;NAME&lt;/th&gt;<br>      &lt;th&gt;STATUS&lt;/th&gt;<br>      &lt;th&gt;REASON&lt;/th&gt;<br>    &lt;/tr&gt;<br>  &lt;/tbody&gt;<br>&lt;/table&gt;</pre></td>
  </tr>
</tbody>
</table>

**Comment by strangelookingnerd** [comment]
On first look it seems that the `MarkupFormatter` (I assume you are using https://github.com/jenkinsci/antisamy-markup-formatter-plugin) does remove the `class` attributes. I will investigate a little further to find out if and how one could change that and let you know.

**Comment by marslo** [comment]
thanks a lot @strangelookingnerd !

**Comment by strangelookingnerd** [comment]
Digging a little deeper I can confirm above assumption. One way of working around that would be to use the https://plugins.jenkins.io/custom-markup-formatter/ and explicitly allow `class` attributes in the formatted HTML. I did not dive too much into it, but looking at the docs it should be straight forward.

Another option would be to disable the markup formatter globally via https://plugins.jenkins.io/anything-goes-formatter/ which I would not really recommend.

The third option is to disable markup formatting in the plugin which currently is not supported and I would rather keep that way in order to prevent security issues further down the road.

**Comment by jangalda-nsc** [comment]
I was able to get formatted table using `bigtable` class.
`addSummary(id: 'my-table', text: table, cssClass: 'bigtable', icon: 'icon-clipboard')`

I have Markup Formatted set to `Safe HTML`.
Above code requires Badge plugin version 2.6+, due to #210  issue

**Comment by marslo** [comment]
Hi @jangalda-nsc,

sorry for the late reply.
the `bigtable` css works to me thanks:

- light mode:

  <img width="416" alt="Image" src="https://github.com/user-attachments/assets/5bf130e7-00b7-4beb-b8c1-ad7af20e4f99" />

- dark mode:

  <img width="407" alt="Image" src="https://github.com/user-attachments/assets/128c3a54-d890-4ce1-8dff-6f21fc6fa84d" />
