### ISSUE TITLE
HTML Filtering configurable via CasC

### ISSUE THREAD

**Issue by nattofriends** [jenkinsci/badge-plugin#26]
**Is your feature request related to a problem? Please describe.**
The global configuration added in #20 should be configurable via Configuration-as-Code.

**Describe the solution you'd like**
I can configure the HTML Filtering global configuration of the plugin via Configuration-as-Code.

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**
No additional context.

**Comment by bakito** [comment]
Hi @nattofriends 

Thank you for your input.

This should already be possible.

Have you tried the following?
`
unclassified:
  badgePlugin:
    disableFormatHTML: true
`

Regards,
bakito

**Comment by nattofriends** [comment]
I tried looking for it in the Configuration-as-Code export but I was not looking on a master where I had enabled the option already. Thanks for the help.

**Comment by bakito** [comment]
np
