### ISSUE TITLE
Question: where or how does createSummary look for icons?

### ISSUE THREAD

**Issue by martinda** [jenkinsci/badge-plugin#68]
It is not clear to me where the `createSummary` step looks for icons or how to properly specify icons.

1. Specifically, does it look at the new [Symbols](https://www.jenkins.io/doc/developer/views/symbols/)
2. Does this plugin need a migration as described in [Icon path to icon class migration](https://www.jenkins.io/doc/developer/views/icon-path-to-icon-class-migration/)
3. The example in README uses `/static/8361d0d6/images/16x16/help.png` but how do I write common code with this when the Pipeline library is used on multiple different servers?

Thank you

**Comment by mill1000** [comment]
I found I was able to successfully use symbols with the following
```groovy
script {
    summary = createSummary icon: 'icon-document icon-md'
    summary.appendText("Stuff")
}
```
